### ISSUE TITLE
[BUG] Uncaught TypeError: sharedType.toJSON is not a function

### ISSUE THREAD

**Issue by arvinxx** [joebobmiles/zustand-middleware-yjs#49]
**Describe the bug**

I'm try to intergrate into our product, but I found a problem:

```
Uncaught TypeError: sharedType.toJSON is not a function
    at patchSharedType (yjs.mjs:293:1)
    at yjs.mjs:341:1
    at Array.forEach (<anonymous>)
    at patchSharedType (yjs.mjs:294:1)
    at yjs.mjs:344:1
    at Array.forEach (<anonymous>)
    at patchSharedType (yjs.mjs:294:1)
    at yjs.mjs:341:1
    at Array.forEach (<anonymous>)
    at patchSharedType (yjs.mjs:294:1)
    at yjs.mjs:341:1
    at Array.forEach (<anonymous>)
    at patchSharedType (yjs.mjs:294:1)
    at yjs.mjs:464:1
    at transact (yjs.mjs:3292:1)
    at Doc.transact (yjs.mjs:505:1)
    at yjs.mjs:463:1
```

<img width="524" alt="image" src="https://github.com/joebobmiles/zustand-middleware-yjs/assets/28616219/9b8e9324-632f-49e4-9205-a61c061a40e4">

here is my data snapshot: 

<img width="959" alt="image" src="https://github.com/joebobmiles/zustand-middleware-yjs/assets/28616219/97da1d65-415f-4848-aa8e-8ddfbb6993ab">

**Screenshots**

**Versions (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  1.3.0

**Additional context**

**Comment by joebobmiles** [comment]
I'm going to need a minimal reproduction to debug this. Can you set up a CodeSandbox or repo that reproduces this error? Or at least the full JSON of your data snapshot instead of a screencap?

**Comment by alexkreidler** [comment]
I've got the same error. I made a [CodeSandbox example](https://codesandbox.io/p/github/codesandbox/codesandbox-template-vite-react/csb-6yx57c/yjs-zustand-issue?file=/src/state.ts:11,43).

Reproduction steps:
1. Open devtools
2. Click on test
3. Click on test2. You should see the error in the console
(You may have to open a second tab with the same page before step 2/3)
4. If you repeat clicking on any of the text items you should see the error repeat

I initially thought it might be an issue with the `immer` Zustand extension. But I removed it from the code and still got the error.

**Comment by joebobmiles** [comment]
Thanks Alex!

From debugging your example, the bug is obvious: I forgot to convert strings to YText objects before shoving them in Yjs...

I'll get that fixed as soon as I have the time!

**Comment by joebobmiles** [comment]
Release 1.3.1 fixes this issue, so going to close for now. If something else is broken, don't hesitate to reopen it!
